---
- name: Config - Symlink
  file:
    src: /opt/horizon/etc/horizon-httpd.conf
    dest: /etc/nginx/conf.d/horizon.conf
    state: link
    force: yes

- name: Config - Update licence
  ansible.builtin.copy:
    src: "{{ horizon_licence_src_path }}"
    dest: "{{ horizon_licence_dest_path }}"

- name: Config - File creation /etc/default/horizon
  ansible.builtin.template:
    src: "{{ path_to_template_default_horizon }}"
    dest: "{{ path_to_default_horizon }}"


- name: Config - Update hosts allowed
  ansible.builtin.template:
    src: "{{ path_to_template_hosts_allowed }}"
    dest: "{{ path_to_hosts_allowed }}"

